[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastapi-constance"
version = "0.0.1"
description = "Dynamic configuration management for FastAPI, inspired by Django Constance."
readme = "README.md"
license = "MIT"
authors = [{name="Aoun", email="zaoun123@gmail.com"}]
requires-python = ">=3.8"

dependencies = [
    "fastapi>=0.115.0",
    "sqlalchemy>=2.0",
    "sqlmodel>=0.0.16",
    "sqladmin>=0.20.0",
]

[project.urls]
Homepage = "https://github.com/muhammadaounzaidi/fastapi-constance/"
